[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[project]
name = "eetc-utils"
version = "1.7.0"
description = "EETC Utils Library"
authors = [
    { name = "East Empire Trading Company", email = "eastempiretradingcompany2019@gmail.com" },
    { name = "Stefan Delic", email = "einfach.jung1@gmail.com" },
    { name = "Milos Dovedan", email = "dovedanmilosh@gmail.com" },
]
maintainers = [
    { name = "East Empire Trading Company", email = "eastempiretradingcompany2019@gmail.com" },
    { name = "Stefan Delic", email = "einfach.jung1@gmail.com" },
    { name = "Milos Dovedan", email = "dovedanmilosh@gmail.com" },
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=2.3.3,<4.0.0",
    "numpy>=2.3.4,<3.0.0",
    "arch>=8.0.0,<9.0.0",
    "requests>=2.28.0,<3.0.0",
    "anthropic>=1.6.0,<2.0.0",
]

[project.urls]
Homepage = "https://github.com/east-empire-trading-company/eetc-utils"
Repository = "https://github.com/east-empire-trading-company/eetc-utils"
"Bug Tracker" = "https://github.com/east-empire-trading-company/eetc-utils/issues"

[dependency-groups]
dev = [
    "black>=25.9.0,<26.0.0",
    "pytest>=9.0.1,<10.0.0",
]

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true
